owncloud/documents

css/style.css, js/documents.js, js/widgets/ocClose.js
Please review @owncloud/designers @VicDeo
=> better style for close button

README.md
Update build target to build editor along with with webodf
=> Fix build target

lib/db/session.php, lib/filter.php, lib/storage.php
Do not start session for unknown filetypes
=> Skip non-supported mimes

appinfo/info.xml
@DeepDiver1975
owncloud/core#13706
=> Remove is shipped

lib/db/session.php, lib/filter.php, lib/storage.php
Backport of https://github.com/owncloud/documents/pull/436
=> [stable7] Skip non-supported mimes

lib/db/session.php, lib/filter.php, lib/storage.php
Backport of #436
Conflicts resolved:
lib/db/session.php
=> [stable6] Skip non-supported mimes

index.php, js/documents.js
Backport of https://github.com/owncloud/documents/pull/467
=> [stable8] Enable by default. Skip loading if disabled

controller/sessioncontroller.php, js/ServerFactory.js, lib/genesis.php
Fixes https://github.com/owncloud/documents/issues/472
=> Kill OC_FileProxy references

lib/config.php, lib/converter.php
Make sure that the LibreOffice configuration folder ends up in the temp folder of the instance
=> LibreOffice config should be in instance temp folder

appinfo/info.xml
Ref https://github.com/owncloud/documents/issues/479
=> Update appinfo to actual state

js/ServerFactory.js, js/viewer/viewer.js
Backport token encoding to stable8
Ref https://github.com/owncloud/documents/issues/463
=> [Stable8] encode token

appinfo/app.php, js/admin.js, js/personal.js, js/settings.js, js/viewer/viewer.js, js/widgets/ocToolbar.js
=> Use closure for navigation. 

appinfo/app.php
Similar/same fix as in calendar with https://github.com/owncloud/calendar/commit/3e4a1e1a241479c2c3c5be60379c520c421ce8c0 and contacts https://github.com/owncloud/contacts/pull/973
=> Fix "Undefined index: REQUEST_URI" on cron runs

js/viewer/viewer.js
backport of https://github.com/owncloud/documents/pull/522
=> Rename variable. Fixes #505

public.php
=> Remove unused stylesheet

lib/db/op.php
Backport of https://github.com/owncloud/documents/pull/533
=> [Stable8.1] WebODF uses timestamps with milliseconds

lib/db/op.php
=> WebODF uses timestamps with milliseconds

lib/db/op.php
=> [Stable8] milliseconds

controller/documentcontroller.php, js/documents.js
Fixes https://github.com/owncloud/documents/issues/425
Conflicts:
controller/documentcontroller.php
=> [stable8.1] Load previews only for registered providers

lib/db.php, lib/db/session.php
Stable8.1 backport of critical changes from https://github.com/owncloud/documents/pull/536
Fixes https://github.com/owncloud/documents/issues/528
=> Zero as a last inserted memberId

css/share.css, js/share.js, templates/documents.php
=> Fix share dropdown

lib/converter.php
=> No more get_temp_dir

lib/converter.php
backport https://github.com/owncloud/documents/pull/560
=> [Stable8.2] No more get_temp_dir

appinfo/info.xml
Cross-test results https://github.com/owncloud/documents/issues/507#issuecomment-150023939
Fixes #558
=> Require OC 8.0.x

appinfo/info.xml
Cross-test results https://github.com/owncloud/documents/issues/507#issuecomment-150023939
=> Require 8.1 or 8.2

appinfo/info.xml
Cross-test results https://github.com/owncloud/documents/issues/507#issuecomment-150023939
=> Require 8.1 at least

js/viewer/viewer.js
Try to load index.php file but it doesn't exist. Use generateURL instead
=> Fix editing document problem

js/viewer/viewer.js
Try to load index.php file but it doesn't exist. Use generateURL instead
Backport of https://github.com/owncloud/documents/pull/589
=> [Stable8.2] Fix editing document problem

controller/documentcontroller.php
getData on search result is not always an array now
#609
=> Fixes broken documents view 

lib/appconfig.php
Backport of https://github.com/owncloud/documents/pull/605
=> [Stable8.2] Fix user value set 

controller/documentcontroller.php
=> Get path relative to files dir

appinfo/app.php
=> Add event listener for files app

controller/documentcontroller.php, lib/file.php, tests/controller/documentcontrollertest.php
=> [Stable 9] getPath throw exception since 9.0

controller/documentcontroller.php
=> [Stable9] Get path relative to files dir

appinfo/app.php
=> [Stable9] fix 625

lib/file.php
@VicDeo @DeepDiver1975 @butonic 
To be backported to:
- stable9.1
- stable9
=> Cast share id to string

controller/documentcontroller.php, js/documents.js, templates/documents.php
=> [stable9.1] Fix upload

js/documents.js
=> [Stable9] Fix upload

js/documents.js
=> [Stable8.2] fix upload

js/share.js
@VicDeo @DeepDiver1975 
Backports will follow.
=> More escaping in share dropdown

js/share.js
Backport https://github.com/owncloud/documents/pull/645
@DeepDiver1975 @VicDeo
=> [stable9.1] More escaping in share dropdown

js/share.js
Backport https://github.com/owncloud/documents/pull/645
@DeepDiver1975 @VicDeo
=> [stable9] More escaping in share dropdown

js/share.js
Backport https://github.com/owncloud/documents/pull/645
@DeepDiver1975 @VicDeo
=> [stable8.2] More escaping in share dropdown
